### ISSUE TITLE
Checkbox, radio selection and pagination

### ISSUE THREAD

**Issue by cyberwani** [luis-almeida/filtrify#9]
I am working on a project in which I need multiple filters. Like, user has selected the category1 in categories, and he want to select type. He can select type1 and also he can select the type2. If he has selected two type and one category then it needs to display items from category1 and also in type1 and type2.

And, other setting require for pagination. i need to set limit of items. Like If I want to set limit to 9, And there are 15 items after filtering, then it will display pagination with 2 pages.

Is this possible?

**Comment by luis-almeida** [comment]
@cyberwani I'm not really sure if I understood your first question but it is possible to filter items by multiple tags from different categories. Did you see the [Multiple categories](http://luis-almeida.github.com/filtrify/movies.html) demo?

In your second question I think you're referring to the pagination plugin. 
You can change the number of items per page if you want.
What exactly do you mean by limit?

**Comment by cyberwani** [comment]
I make mistake to describe the issue.

Actually I am working on a project with portfolios. In which we have to display the portfolio with two filter. First, the "Category", for which I want simple button or Radio button like functionality. Where user can select any category.
And, for 2nd filter "Features" i want check-box selection system. Where user can select multiple "Features".

By this use can view the portfolio entries which is in "Category1" and contains the features like "Feature1" and "Feature2".

So, it will looks like this http://awesomescreenshot.com/03a3l1p65

In your demo link when I Selects the genre "Action" then it sorts all data with "Action". And after when i select any actor then it filters that actor in "genre".

In my 2nd question i was asking for for pagination. Its clear now.
Thanks

**Comment by luis-almeida** [comment]
Filtrify uses the "and" logical operator between categories. 
It will always show results that have all the tags that you selected in each category.

In your case, you are treating "features" as a subcategory. You want something like this:
"Select all the items from category 1 that have feature 2 OR feature 3 OR feature 4".

But filtrify will only let you do this:
"Select all the items from category 1 that have feature 2 AND feature 3 AND feature 4".

It is not possible to accomplish want you want to do without changing the internal filter function.
Maybe Isotope would be a better solution for this case because you have complete control over the filter functionality.

Hope it helped :)
I'm closing this issue and I'm labeling it as a question.
